CREATE TABLE `ivi_scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`contNo` varchar(50),
	`companyName` varchar(255),
	`baseIviScore` decimal(5,2) NOT NULL,
	`hScoreAdjustment` decimal(5,2) NOT NULL DEFAULT '0',
	`eScoreAdjustment` decimal(5,2) NOT NULL DEFAULT '0',
	`uScoreAdjustment` decimal(5,2) NOT NULL DEFAULT '0',
	`projectedHScore` decimal(5,2) NOT NULL,
	`projectedEScore` decimal(5,2) NOT NULL,
	`projectedUScore` decimal(5,2) NOT NULL,
	`projectedIviScore` decimal(5,2) NOT NULL,
	`projectedRiskCategory` enum('Low','Medium','High') NOT NULL,
	`timeHorizonMonths` int NOT NULL DEFAULT 12,
	`monthlyProjections` text,
	`assumptions` text,
	`isFavorite` boolean NOT NULL DEFAULT false,
	`isShared` boolean NOT NULL DEFAULT false,
	`tags` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ivi_scenarios_id` PRIMARY KEY(`id`)
);
